### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by Vi-dot** [KDAB/android_openssl#1]
Hello,

First, thank you for submitting this repo.

Even with your libs in the APK, I got the message : 
```
QSslSocket::connectToHostEncrypted: TLS initialization failed
```

I use Qt 5.12.4

When I try with Qt 5.12.3 and openssl-1.0.2o, SSL is working.

**Comment by GregoryError** [comment]
I have the same issue as man above, when try to make a libs use different versions of openssl with Qt 5.13 for target Android arm x64! Your libs I gonna try tonight. Hope it`ll work properly!

**Comment by GregoryError** [comment]
> Hello,
> 
> First, thank you for submitting this repo.
> 
> Even with your libs in the APK, I got the message :
> 
> ```
> QSslSocket::connectToHostEncrypted: TLS initialization failed
> ```
> 
> I use Qt 5.12.4
> 
> When I try with Qt 5.12.3 and openssl-1.0.2o, SSL is working.

Which archetecture of Android you use with? x64?

**Comment by Vi-dot** [comment]
I got this error with both architectures : 
- **armeabi-v7a** with arm/libcrypto_1_1.so and arm/libssl_1_1.so
- **arm64-v8a** with arm64/libcrypto_1_1.so and arm64/libssl_1_1.so

**Comment by GregoryError** [comment]
> I got this error with both architectures :
> 
> * **armeabi-v7a** with arm/libcrypto_1_1.so and arm/libssl_1_1.so
> * **arm64-v8a** with arm64/libcrypto_1_1.so and arm64/libssl_1_1.so

Yeee! It works! Just now I tried it Qt 5.13 arm64-v8a with NDK 19c. And it finally works!

**Comment by GregoryError** [comment]
I`d been trying to solve this for a week! ... tried a lot of scripts with no result and now it works! Cool! Thanks!

**Comment by bog-dan-ro** [comment]
For 5.12.4 & 5.13.0 please use https://github.com/KDAB/android_openssl/commit/95b31fe9ffac7cff6b361132e3a0d2550364e6c0 the master is for 5.12.5 and 5.13.1 see https://codereview.qt-project.org/c/qt/qtbase/+/267324 for more info.

**Comment by Vi-dot** [comment]
Thank you it works now 👍

**Comment by bog-dan-ro** [comment]
> Thank you it works now

Be aware that on Android 5 (API 21) 5.12.4 & 5.13.0 don't work.

**Comment by ekke** [comment]
thx for this info
hopefully 5.13.1 will come out soon to be able to publish apps for 32/64 bit with OpenSSL 1.1.1
