### ISSUE TITLE
Crash when try to debug app

### ISSUE THREAD

**Issue by sagiadinos** [KDAB/android_openssl#10]
Try to debug app while this libraries are included causes a crash. See image
![debugger_crash](https://user-images.githubusercontent.com/16494822/75634497-b7225700-5c0e-11ea-93f0-feb75f87e863.png)

Qt Creator 4.11.1 and an earlier maybe 4.10.x
Qt 5.12.6 and 5.12.7
Android 9, but also in Android 7.1
Kubuntu 19.10

Workaround : Temporary commenting the entry in *.pro file

**Comment by bog-dan-ro** [comment]
It seems this is a gdb problem, please report this issue to https://bugreports.qt.io we'll see what we can do about it. Probably an workaround will be to disable signals catch in gdb, but QtCreator folks have more experience than me on this matter.
