### ISSUE TITLE
Qt 5.12.4 and Android 5

### ISSUE THREAD

**Issue by vdaele** [KDAB/android_openssl#13]
Thank you for these precompiled libs!

You write "Be aware that on Android 5 (API 21) these libs names are clashing with the system SSL libs which are using OpenSSL 1.0".  
Is this the reason I get an error like "java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "EVP_camellia_128_cbc" referenced by ...."

Would this be solved by using static libraries (libssl.a and libcrypto.a)? 
If so, would it be possible to also provide these static libs (or give some guidance on how to build them?)

**Comment by bialasjaroslaw** [comment]
For Android 5 (API 21), Qt developers advise to use SSL with _1_1 prefix - see here https://doc.qt.io/qt-5/android-openssl-support.html
Just use libraries from latest directory and you will be fine. To use static libs, you have to compile Qt libraries by yourself and during configuration/make stage just point out to directory containing libcrypto.a and libssl.a files 
In my case it was 

`OPENSSL_LIBS='-L/home/user/android_openssl/static/lib/arm/ -lssl -lcrypto' ./configure ${configue_opts} -openssl-linked -I/home/user/android_openssl/static/include/
`

**Comment by bog-dan-ro** [comment]
We've changed it in the recent commits, now if you use head of master it should automatically detect which qt version are you using and use the apropiate libs.
