### ISSUE TITLE
Shared library architecture aarch64 is not compatible with target architecture armv8-a

### ISSUE THREAD

**Issue by mbruel** [KDAB/android_openssl#14]
Hi,

I tried to include your pri last week on a simple example and it was working without any issue.
Now on another app I'm getting a compatible issue for libcrypto_1_1.
Weird thing, the first project that was working is now failing with the same issue...
Here is the full log:
```
The command "/home/bruel/android/sdk/platform-tools/adb" terminated with exit code 1.
adb: error: listener 'tcp:33109' not found
00:28:02: Debugging starts
I el.test.sendSM: Late-enabling -Xcheck:jni
W ActivityThread: Application com.mbruel.test.sendSMS is waiting for the debugger on port 8100...
The command "/home/bruel/android/sdk/platform-tools/adb" terminated with exit code 1.
adb: error: listener 'tcp:5038' not found
I System.out: Sending WAIT chunk
Could not load shared library symbols for 225 libraries, e.g. /system/lib/libandroid_runtime.so.
Use the "info sharedlibrary" command to see the complete listing.
Do you need "set solib-search-path" or "set sysroot"?I System.out: Debugger has connected
I System.out: waiting for debugger to settle...
I chatty  : uid=10390(com.mbruel.test.sendSMS) identical 6 lines
I System.out: waiting for debugger to settle...
Could not load shared library symbols for /system/lib/libqti_performance.so.
Do you need "set solib-search-path" or "set sysroot"?Could not load shared library symbols for /system/lib/vendor.qti.hardware.iop@2.0.so.
Do you need "set solib-search-path" or "set sysroot"?I System.out: debugger has settled (1403)
I Perf    : Connecting to perf service.
W System  : ClassLoader referenced unknown path:
Could not load shared library symbols for /data/app/com.mbruel.test.sendSMS--1Mx2gP70yNDwuF88ADDmw==/lib/arm/libc++_shared.so.
Do you need "set solib-search-path" or "set sysroot"?I QtCore  : Start
I Qt      : qt started
`/home/bruel/Documents/android/android_openssl/latest/arm64/libcrypto_1_1.so': Shared library architecture aarch64 is not compatible with target architecture armv8-a.
.dynamic section for "/home/bruel/Documents/android/android_openssl/latest/arm64/libcrypto_1_1.so" is not at the expected address (wrong library or version mismatch?)
```
Any idea why I'm getting that?
I've just pulled your latest changes and it does the same.
I'm using Qt v5.14.1, android-ndk-21, android build sdk 29, Target sdk: API 28: Android 9.
my phone has a Snapdragon 625 processor.

I suppose it is just a bad setting somewhere but I've no clue what to do...
Thanks in advance for the help ;)

**Comment by mbruel** [comment]
After many tests, I've managed to avoid the crash by re-compiling openssl **without assembler code**.
Maybe you should consider do the same for your libs?

```
#!/bin/sh
ARCH=android-arm64
ANDROID_API=28
NDK_DIR=/home/bruel/android/android-ndk-r21
NDK_TOOLCHAIN=$NDK_DIR/toolchains/llvm/prebuilt/linux-x86_64/bin

export ANDROID_NDK_HOME=$NDK_DIR
export PATH=$NDK_TOOLCHAIN:$PATH

./Configure no-asm no-tests $ARCH -D__ANDROID_API__=$ANDROID_API -funwind-tables -fexceptions -frtti
make
```

**Comment by bog-dan-ro** [comment]
@mbruel thanks a lot for your report, sadly I can't reproduce your problem...
Can you please give more info:
- what sha are you using (I tested 67325bb)
- what device are you using
- what android version

Compiling openssl with no-asm will make it run slower and I'd like to avoid that flag if possible.

**Comment by mbruel** [comment]
Hi,

I'm using the same sha.
As I said, it was working the first times I tried with an older version and I don't know for what reason I started to get this crash. So I pulled last Friday and I've now openssl to 1.1.1f.
My first tries were like 2 weeks ago, so I'd say it was your openssl 1.1.1d.

- My device is a [Xiaomi Redmi note 5.](https://en.wikipedia.org/wiki/Redmi_Note_5).
- I've the latest update on it: MIUI Global 11.0.3.0, with Android 9 PKQ1.180904.001

Here is the stack assembly code I'm getting on the crash, stopping in line 6.
```
0xd352f994                  00 f0 20 e3  nop	{0}
0xd352f998                  00 f0 20 e3  nop	{0}
0xd352f99c                  00 f0 20 e3  nop	{0}
0xd352f9a0                  50 01 20 f2  vorr	q0, q0, q0
0xd352f9a4                  1e ff 2f e1  bx	lr
0xd352f9a8                  1e 0f 51 ec  mrrc	15, 1, r0, r1, cr14
0xd352f9ac                  1e ff 2f e1  bx	lr
0xd352f9b0                  00 03 b0 f3  aese.8	q0, q0
0xd352f9b4                  1e ff 2f e1  bx	lr
0xd352f9b8                  40 0c 00 f2  sha1c.32	q0, q0, q0
0xd352f9bc                  1e ff 2f e1  bx	lr
0xd352f9c0                  40 0c 00 f3  sha256h.32	q0, q0, q0
0xd352f9c4                  1e ff 2f e1  bx	lr
0xd352f9c8                  00 0e a0 f2  vmull.p64	q0, d0, d0
0xd352f9cc                  1e ff 2f e1  bx	lr
0xd352f9d0                  68 00 9f e5  ldr	r0, [pc, #104]	; 0xd352fa40
0xd352f9d4                  64 10 8f e2  add	r1, pc, #100, 0	; 0x64
0xd352f9d8                  00 00 91 e7  ldr	r0, [r1, r0]
0xd352f9dc                  02 20 22 e0  eor	r2, r2, r2
0xd352f9e0                  03 30 23 e0  eor	r3, r3, r3
0xd352f9e4                  0c c0 2c e0  eor	r12, r12, r12
0xd352f9e8                  01 00 10 e3  tst	r0, #1, 0
0xd352f9ec                  0b 00 00 0a  beq	0xd352fa20
```

As it was breaking on assembler code, I've tried to compile it with the no-asm option and it worked. (I'm running openssl 1.1.d at the moment, the same used for Qt v5.14.1)

Here is a snapshot of my crash.
![snapshot](https://i.ibb.co/yFM5ZnX/Screenshot-2020-04-08-13-47-26.png)
This app is using QtLocation to fetch the location of the GPS position using OpenStreetMap which has an HTTPS API.

I've another example that is crashing the way, when I'm just trying to access a REST API on HTTPS using QNetworkAccessManager::get.

**Comment by bog-dan-ro** [comment]
@mbruel Ah, it hangs in debug mode, I think I saw that problem a few times.
Can you please try to run the application (using the run button not the debug) and see if it still crashing?

**Comment by mbruel** [comment]
hum... seems to work now when I just run instead of debug.

`D libtestAdroid_armeabi-v7a.so: "SSL support: yes, build version: OpenSSL 1.1.1d  10 Sep 2019, system version: OpenSSL 1.1.1f  31 Mar 2020"
`
But I'm pretty sure I tried to compile in release mode and install the apk manually on the device and it wasn't working anymore. So I'm wondering if it is stable... well I'll let you know if it happens again but I'm mainly using the debug mode at the moment...

Maybe It would be useful then if you could provide a no-asm version for DEBUG mode and keep the normal one for release?

Something unrelated, I'm stuck trying to test [your service example](https://www.kdab.com/qt-android-create-android-service-using-qt/?unapproved=151217&moderation-hash=24b57fd38e972d2a790a4411076dccc2#comment-151217). If you've some time, I'd really appreciate a bit of help ;)

Cheers.
Feel free to close the ticket then if this happens only in Debug...

**Comment by bog-dan-ro** [comment]
@mbruel Thanks a lot for checking it !

It doesn't matter if you'll compile it in debug or release mode as long as you hit debug button ;-)
Anyway, I'll keep this issue open to create a `no-asm` libs set for debug only builds.

I hope next week I'll have more time to check the service example...

**Comment by Issam-b** [comment]
@mbruel BTW, you can check those two additions for services with Qt https://codereview.qt-project.org/c/qt/qtandroidextras/+/296449 and https://codereview.qt-project.org/c/qt/qtandroidextras/+/296457. Feel free to comment and review :)
