### ISSUE TITLE
TLS initialization failed

### ISSUE THREAD

**Issue by Refinath** [KDAB/android_openssl#3]
qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed

Getting this issue and unable to connect to internet from application

**Comment by sbrown89** [comment]
Change the script to remove the 1_1 extension. its looking for the standard libssl and crypto names. I did this on my fork as well as dropped the version number to 1b to aligin with qt 5.13. https://github.com/sbrown89/android_openssl

Doing so ... everything will work as expected.

**Comment by bog-dan-ro** [comment]
Please read the README.md
