### ISSUE TITLE
How to add dependencies if TARGET is a library

### ISSUE THREAD

**Issue by matzrm** [KDAB/android_openssl#34]
Hello,

I'm trying to create a qt android library to use it in Android Studio. I only need of QtCore and QtNetwork with SSL supports.

For my scope I started with a new Android Studio project with Native support and I added to the CMakeLists.txt all the stuff to load Qt6Core and Qt6Network. For the SSL support I have cloned the android_openssl and I have included it in this way

if(ANDROID)
    include(${SSL_LIB}\\CMakeLists.txt)
endif()
But when the target is a LIBRARY seems there's no way to add the dependecies to the project so, also if QT_ANDROID_EXTRA_LIBS is setted, libcrypto and libssl and the other plugins are not added to the project and QNetwork starts without the SSL supports.

Anyone can help?

**Comment by bog-dan-ro** [comment]
You need to add `QT_ANDROID_EXTRA_LIBS` to the application not to the library.
