### ISSUE TITLE
Qt 6.5 OpenSSL 3

### ISSUE THREAD

**Issue by demiantres** [KDAB/android_openssl#37]
Qt 6.5 switched to OpenSSL 3. Is there a chance to get support for this?

**Comment by JamesMBallard** [comment]
+1 for this one.

**Comment by kebekus** [comment]
+1 for this one

**Comment by bog-dan-ro** [comment]
Pushed a new fix to `qt_6.5` branch, please give it a try. If no issues will be reported I'll merge it into master.
