### ISSUE TITLE
dlopen failure

### ISSUE THREAD

**Issue by jheaff1** [KDAB/android_openssl#39]
After migrating my app to Qt 6.5.0, and am now using OpenSSL 3 provided by android_openssl, I observed the following error 

`: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcrypto.so" not found: needed by /data/app/~~nv-NYGsxD8h1JbRF7mG3AA==/com.myapp-RSMRM3Ki5qWP-hfAZG2lAg==/lib/arm/libssl_3.so in namespace classloader-namespace`

It seems that libssl_3.so depends on `libcrypto.so` even though the file provided by this repo is named `libcrypto_3.so`. If I copy `libcrypto_3.so` to `libcrypto.so` the issue goes away

**Comment by bog-dan-ro** [comment]
@jheaff1 can you please check if using https://github.com/KDAB/android_openssl/pull/38 is better ?

**Comment by bog-dan-ro** [comment]
ah, I know what's the problem, I'll try to fix it soon.

**Comment by bog-dan-ro** [comment]
@jheaff1 should be fixed now, please try again (forced push the qt 6.5 branch).

**Comment by jheaff1** [comment]
Thanks for looking into this. I now get the following error:

```
ava.lang.UnsatisfiedLinkError: dlopen failed: cannot find "libcrypto_3.so" from verneed[0] in DT_NEEDED list for "/data/app/~~ThKubQ5xx5IuByd4fN6i1Q==/com.myapp-5sYYFnIuRJCJ4AcCDcY6eQ==/lib/arm/libssl_3.so"
```

Even though if I unzip my apk I can see libcrypto_3.so within it, along with libssl_3.so.

**Comment by jheaff1** [comment]
@bog-dan-ro It works now, thanks!
