### ISSUE TITLE
ANDROID_ABI instead of ANDROID_TARGET_ARCH?

### ISSUE THREAD

**Issue by malachib** [KDAB/android_openssl#41]
I'm making a lot of assumptions here, so feel free to whack this down

One of my Qt Creator installs doesn't populate ANDROID_TARGET_ARCH.  Presumably this is because there's no device configured for it yet.  However, regardless of that, ANDROID_ABI is always assigned.  Presuming ANDROID_ABI mates directly to the chosen compiler/NDK, that makes sense.

If all that is true, it seems more sensible to use ANDROID_ABI than ANDROID_TARGET_ARCH in the CMakeLists.txt file.  What do you think?

**Comment by DarhonSoftware** [comment]
I can confirm that the current CMakeLists.txt doesn't work, but I changed **ANDROID_TARGET_ARCH** for **CMAKE_ANDROID_ARCH_ABI** and it worked well for me.

**Comment by rgriebl** [comment]
Same problem here. Creator 10.0, Qt 6.5.0
Needs a `set(ANDROID_TARGET_ARCH ${CMAKE_ANDROID_ARCH_ABI})` before including the CMakeLists.txt
