### ISSUE TITLE
missing x64 for 1.0.x

### ISSUE THREAD

**Issue by steelbytes** [KDAB/android_openssl#5]
missing x64 for 1.0.x

**Comment by bog-dan-ro** [comment]
I had difficulties to build it for x86_64 that's why it's missing. Any patches are welcome ;-)

**Comment by bog-dan-ro** [comment]
OpenSSL 1.0 is not supported anymore by upstream, therefore I'm going to close this bug,

**Comment by TechComet** [comment]
I using 64bit change output dll name
