### ISSUE TITLE
I do everything,but not work

### ISSUE THREAD

**Issue by fanhenghui** [KDAB/android_openssl#6]
my envriment is qt5.13.0, android-ndk-r19c, android 7.1 armv7a
event complie openssl with myself
but the result is the same 
---------------------------------------------------------
I/art     (10870): Late-enabling -Xcheck:jni
I/ActivityManager( 1735): Start proc 10870:com.eltyl.EltNewControl/u0a34 for activity com.eltyl.EltNewControl/org.qtproject.qt5.android.bindings.QtActivity
D/houdini (10870): [10870] Initialize library(version: 5.0.7b_x.48396 RELEASE)... successfully.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libc++_shared.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libQt5Core.so for ClassLoader by Native Bridge.
I/QtCore  (10870): Start
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libQt5Gui.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libQt5Network.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libQt5WebSockets.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libQt5Widgets.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/data/com.eltyl.EltNewControl/qt-reserved-files/plugins/platforms/android/libqtforandroid.so for ClassLoader by Native Bridge.
I/Qt      (10870): qt started
D/houdini (10870): [10889] Added shared library /data/data/com.eltyl.EltNewControl/qt-reserved-files/plugins/bearer/libqandroidbearer.so for ClassLoader by Native Bridge.
D/houdini (10870): [10889] Added shared library /data/app/com.eltyl.EltNewControl-2/lib/arm/libEltNewControl.so for ClassLoader by Native Bridge.
D/OpenGLRenderer(10870): Use EGL_SWAP_BEHAVIOR_PRESERVED: true
D/OpenGLRenderer(10870): Enabling debug mode 0
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_ssl
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_init_crypto
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve ASN1_STRING_get0_data
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve EVP_CIPHER_CTX_reset
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve RSA_bits
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_new_null
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_push
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_free
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_num
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_pop_free
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OPENSSL_sk_value
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve DH_get0_pqg
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_options
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_CTX_set_ciphersuites
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_set_psk_use_session_callback
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_get_client_random
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_SESSION_get_master_key
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_session_reused
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve SSL_set_options
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve TLS_method
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve TLS_client_method
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve TLS_server_method
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve X509_up_ref
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve X509_STORE_CTX_get0_chain
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve X509_getm_notBefore
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve X509_getm_notAfter
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve X509_get_version
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version_num
W/libEltNewControl.so(10870): qt.network.ssl: QSslSocket: cannot resolve OpenSSL_version
W/libEltNewControl.so(10870): qt.network.ssl: Incompatible version of OpenSSL
-------------------------------------------------
my pro file is this
contains(ANDROID_TARGET_ARCH,armeabi-v7a) {
    ANDROID_EXTRA_LIBS += \
        $$PWD/openssl/armeabi-v7a/libcrypto.so \
        $$PWD/openssl/armeabi-v7a/libssl.so
}
and I guess that openssl libiary is not load in the android apk,
is it the bug of qt? I donnot know

**Comment by frankosterfeld** [comment]
Which OpenSSL are you using? 5.13.0 requires 1.1.x, and in the latest master the files have the "_1_1" suffix (libcrypto_1_1.so, libssl_1_1.so), did you try with those?

**Comment by fanhenghui** [comment]
yes,if I use _1_1,the console message is:
-------------------------------------------------
D/houdini (11171): [11187] Added shared library /data/data/com.eltyl.EltNewControl/qt-reserved-files/plugins/bearer/libqandroidbearer.so for ClassLoader by Native Bridge.
D/houdini (11171): [11187] Load library /data/app/com.eltyl.EltNewControl-2/lib/arm/libcrypto_1_1.so failed.
E/art     (11171): dlopen("/data/app/com.eltyl.EltNewControl-2/lib/arm/libcrypto_1_1.so", RTLD_LAZY) failed: dlopen failed: "/data/app/com.eltyl.EltNewControl-2/lib/arm/libcrypto_1_1.so" has unexpected e_machine: 40
E/AndroidRuntime(11171): FATAL EXCEPTION: qtMainLoopThread
E/AndroidRuntime(11171): Process: com.eltyl.EltNewControl, PID: 11171
E/AndroidRuntime(11171): java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.eltyl.EltNewControl-2/lib/arm/libcrypto_1_1.so" has unexpected e_machine: 40
E/AndroidRuntime(11171): 	at java.lang.Runtime.load(Runtime.java:331)
E/AndroidRuntime(11171): 	at java.lang.System.load(System.java:981)
E/AndroidRuntime(11171): 	at org.qtproject.qt5.android.QtNative$3.run(QtNative.java:236)
E/AndroidRuntime(11171): 	at org.qtproject.qt5.android.QtThread$2.run(QtThread.java:87)
E/AndroidRuntime(11171): 	at org.qtproject.qt5.android.QtThread$1.run(QtThread.java:61)
E/AndroidRuntime(11171): 	at java.lang.Thread.run(Thread.java:818)

**Comment by fanhenghui** [comment]
thanks, I don not kwon what is wrong, suddenly it work ok
