### ISSUE TITLE
Fails to load

### ISSUE THREAD

**Issue by demiantres** [KDAB/android_openssl#7]
qDebug() << QSslSocket::supportsSsl() << QSslSocket::sslLibraryBuildVersionString() << QSslSocket::sslLibraryVersionString();
produces:
D MyApp: false "OpenSSL 1.1.1b  26 Feb 2019" ""
for both armv7 and arm64 on Qt 5.13.1 snapshot.

**Comment by demiantres** [comment]
Interestingly this one works: https://github.com/orangefour/android-openssl

**Comment by bog-dan-ro** [comment]
What `android_openssl` branch are you using ?

**Comment by demiantres** [comment]
I am using the master branch. I also tried manually compiled 1.1.1b libraries produced with the build_ssl.sh script with the same result.

**Comment by bog-dan-ro** [comment]
I think the 5.13.1 snapshot is too old and it doesn't have the support, please wait for the next snapshot.
5.12.5 snapshot from Aug. 23 should work with no problems.

**Comment by demiantres** [comment]
Ok, thanks.
