### ISSUE TITLE
Cannot be build arm64 

### ISSUE THREAD

**Issue by Zhangsongsong** [KDAB/android_openssl#8]
crypto/aes/aesv8-armx.S:739:2: error: instruction requires: neon
 eor v2.16b,v2.16b,v0.16b
 ^
crypto/aes/aesv8-armx.S:740:2: error: instruction requires: neon
 eor v3.16b,v3.16b,v1.16b
 ^
crypto/aes/aesv8-armx.S:741:2: error: instruction requires: neon
 st1 {v2.16b},[x1],#16
 ^
crypto/aes/aesv8-armx.S:743:2: error: instruction requires: neon
 st1 {v3.16b},[x1]
 ^
make[1]: *** [crypto/aes/aesv8-armx.o] Error 1
make: *** [build_libs] Error 2

**Comment by bog-dan-ro** [comment]
I need more info:
- what NDK are you using
- what host os

**Comment by bog-dan-ro** [comment]
I can't reproduce this issue, please re-open it if needed

**Comment by Zhangsongsong** [comment]
It is ok, the executable does not have permission for NDK on my mac book.
thanks!
