### ISSUE TITLE
Can not include openssl libraries in Qt 5.14.1

### ISSUE THREAD

**Issue by chaunnt** [KDAB/android_openssl#9]
Sorry for this naive question.
I'm making Android project with Qt 5.14.1.
I'm having trouble with openssl libraries.
![Screenshot from 2020-02-13 15-16-45](https://user-images.githubusercontent.com/29053600/74414371-e0ec2780-4e73-11ea-9ddc-683b79df94b8.png)

My last build, I built for ARMv7 and ARMv8 are ok. 
When I'm moving to AAB format, it keep crashing because of this. 

I've tried to include libcryto.so & libssl.so to `android/lib` or `android/libs` (it working on armv7, armv8 build seperately) also try many others from google (jnilibs, etc)

Did you meet this problem before ?

NOTE: I also extract bundle and check, library are in there, same place with other libraries (in /base/lib/ folder)

**Comment by bog-dan-ro** [comment]
From your image it seems your application it's loading the libs from os, which will not work.
Most probably you didn't added those libs using `ANDROID_EXTRA_LIBS` in your `.pro/.pri` file.
